import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/hf/Header";
import Footer from "@/components/hf/Footer";
import { ScrollToTop } from "@/components/sub/ScrollButtons";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-serif" });

export const metadata: Metadata = {
  title: "Home - Aesthetiq Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        "font-serif",
        montserrat.variable,
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <TooltipProvider>
          <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <SidebarInset>
              <Header />
              <ScrollToTop />
              {children}
            </SidebarInset>
          </SidebarProvider>
        </TooltipProvider>
        <Footer />
      </body>
    </html>
  );
}
